version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest --verbose --cov=steppyngstounes --cov-report=html
          name: Test
      - store_artifacts:
          path: htmlcov
          destination: htmlcov

  build-sphinx:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python setup.py build_sphinx
          name: Docs
      - store_artifacts:
          path: build/sphinx/html
          destination: docs

workflows:
  main:
    jobs:
      - build-and-test
      - build-sphinx
